### PR TITLE
OLS-1151: Update the Konflux pipelines to remove enterprise contract warnings

### PR DESCRIPTION
**Pull request by syedriko**
Update the Konflux pipelines to remove enterprise contract warnings

JIRA: https://issues.redhat.com/browse/OLS-1151

### CODE REVIEW

**Comment by syedriko** [comment]
@kyoto PTAL at this one, too, tests pass now

**Comment by kyoto** [comment]
/approve
/lgtm

Override currently broken tests:
/override "Red Hat Konflux / ols-enterprise-contract / lightspeed-console"
/override "Red Hat Konflux / ols-enterprise-contract / pr group syedriko-ols-1151"

**Pull request merged**
